name: Code coverage

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    uses: EpiAware/.github/.github/workflows/coverage.yml@2c7ce73459772f11dad46ac7f456e35f0d296faf
    with:
      julia_version: '1'
    secrets: inherit  # pragma: allowlist secret
