name: Code coverage

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    uses: EpiAware/.github/.github/workflows/coverage.yml@25424fb7f3b6bec94209bab86a42971bd01621ea
    with:
      julia_version: '1'
    secrets: inherit  # pragma: allowlist secret
