name: Doc Preview Cleanup

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  doc-preview-cleanup:
    uses: EpiAware/.github/.github/workflows/docs-preview-cleanup.yml@25424fb7f3b6bec94209bab86a42971bd01621ea
    secrets: inherit  # pragma: allowlist secret
