name: TagBot

on:
  issue_comment:
    types:
      - created
  workflow_dispatch:
    inputs:
      lookback:
        default: "3"

jobs:
  TagBot:
    if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    uses: EpiAware/.github/.github/workflows/tagbot.yml@25424fb7f3b6bec94209bab86a42971bd01621ea
    with:
      lookback: ${{ github.event.inputs.lookback || '3' }}
    secrets: inherit  # pragma: allowlist secret
