name: Test

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: EpiAware/.github/.github/workflows/tests.yml@25424fb7f3b6bec94209bab86a42971bd01621ea
    secrets: inherit  # pragma: allowlist secret

  downgrade-compat:
    uses: EpiAware/.github/.github/workflows/downgrade.yml@25424fb7f3b6bec94209bab86a42971bd01621ea
    secrets: inherit  # pragma: allowlist secret
